### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by siffegh** [M-Reimer/toggleglobalcolors#1]
1. An option to also allow choosing my font selections (override website fonts)
2. A hypertext menu option

**Comment by M-Reimer** [comment]
1. There is a separate Add-on to toggle fonts: https://addons.mozilla.org/de/firefox/addon/togglefonts/
2. What is a "hypertext menu"?

Anyway: This is all out of scope. This Add-on is named "Toggle global colors" and that's what it is meant to do. Nothing more and nothing less.

**Comment by siffegh** [comment]
1. I found that soon after I posted here.
2. I meant context menu.
